export enum EQrPackageTypes {
  Objects = "OBJECTS",
  Services = "SERVICES",
  Users = "USERS",
  UserDevices = "USER_DEVICES",
  UserObjects = "USER_OBJECTS",
  UserServices = "USER_SERVICES",
  Organizations = "ORGANIZATIONS",
  Devices = "DEVICES",
  OrgUsers = "ORG_USERS",
  OrgDevices = "ORG_DEVICES",
  OrgObjects = "ORG_OBJECTS",
  OrgServices = "ORG_SERVICES",
  Witness = "WITNESS",
  ObjectWitnesses = "OBJECT_WITNESSES",
  ServiceWitnesses = "SERVICE_WITNESSES",
  TrophyWalls = "TROPHY_WALLS",
  ACTIONS = "ACTIONS",
}
