export enum EVdtContractType {
  Object = "ObjectVDT",
  Event = "EventVDT",
  Service = "ServiceVDT",
  Device = "DeviceVDT",
  User = "IVDT",
  UserDevices = "UserDeviceVDT",
  UserObjects = "UserObjectVDT",
  UserServices = "UserServiceVDT",
  UserOrganizations = "UserOrganizationVDT",
  Organization = "OVDT",
  OrganizationDevices = "ODVDT",
  OrganizationUsers = "OIVDT",
  OrganizationObjects = "OOVDT",
  OrganizationServices = "OSVDT",
  Witness = "WitnessVDT",
  ObjectWitness = "ObjectWitnessVDT",
  ServiceWitness = "ServiceWitnessVDT",
  CustomerFile = "CustomerFileVDT",
  Action = "ActionVDT",
}
