export enum EAction {
  OfficialRejectVerification = "OFFICIAL_REJECT_VERIFICATION",
  SellerRejectOrder = "SELLER_REJECT_ORDER",
  SellerRejectBid = "SELLER_REJECT_BID",
  BuyerRejectDelivery = "BUYER_REJECT_DELIVERY",
  AdminBlockUser = "ADMIN_BLOCK_USER",
  AdminUnblockUser = "ADMIN_UNBLOCK_USER",
  AdminBlockEndUser = "ADMIN_BLOCK_END_USER",
  AdminUnblockEndUser = "ADMIN_UNBLOCK_END_USER",
  AdminFlagUser = "ADMIN_FLAG_USER",
  AdminUnflagUser = "ADMIN_UNFLAG_USER",
  AdminFlagEndUser = "ADMIN_FLAG_END_USER",
  AdminUnflagEndUser = "ADMIN_UNFLAG_END_USER",
  AdminSuspendOrder = "ADMIN_SUSPEND_ORDER",
  AdminUnsuspendOrder = "ADMIN_UNSUSPEND_ORDER",
  AdminCancelOrder = "ADMIN_CANCEL_ORDER",
  SystemCancelOrder = "SYSTEM_CANCEL_ORDER",
  AdminFlagOrder = "ADMIN_FLAG_ORDER",
  AdminUnflagOrder = "ADMIN_UNFLAG_ORDER",
  UserArchiveS2SToken = "USER_ARCHIVE_S2S_TOKEN",
  AdminDeleteEndUser = "ADMIN_DELETE_END_USER",
  UpdateEndUserRole = "UPDATE_END_USER_ROLE",
  UpdateAdminUserRole = "UPDATE_ADMIN_USER_ROLE",
}
