export enum EPaymentType {
  Card = "CARD",
  ApplePay = "APPLEPAY",
  GooglePay = "GOOGLEPAY", // This type not exists in Paysafe API
  Skrill = "SKRILL",
  Neteller = "NETELLER",
  Paysafecash = "PAYSAFECASH",
  Paysafecard = "PAYSAFECARD",
  Paypal = "PAYPAL",
  Venmo = "VENMO",
  VipPreferred = "VIPPREFERRED",
  Mazooma = "MAZOOMA",
  Sightline = "SIGHTLINE",
  InteracEtransfer = "INTERAC_ETRANSFER",
  RapidTransfer = "RAPID_TRANSFER",
  Skrill1Tap = "SKRILL1TAP",
  Ach = "ACH",
  Eft = "EFT",
  Bacs = "BACS",
  Sepa = "SEPA",
  OnlineBankTransfer = "ONLINE_BANK_TRANSFER",
  Pix = "PIX",
  Khipu = "KHIPU",
  Mach = "MACH",
  BoletoBancario = "BOLETO_BANCARIO",
  SafetypayCash = "SAFETYPAY_CASH",
}
